<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

    <br>
    <br>
    <br>
    <div class="container">
        <div class="col-md-12">
            <?php require VIEWS_PATH . 'includes/messages.phtml' ;?>
        </div>
        <div class="col-md-12">
            <h2>Listagem de despesas </h2>
        </div>
        <div class="col-md-12">
            <h1>Login</h1>
            <form action="<?=HOME;?>/auth/login" class="form-group" method="post">
                E-mail:
                <input name="email" type="email" class="email form-control">
                <br>
                Senha:
                <input name="password" type="password" class="form-control">
                <br>
                <button type="submit" class="btn btn-success">ENTRAR</button>
            </form>
        </div>

    </div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>