<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

    <br>
    <br>
    <br>
    <div class="container">

        <div class="col-md-12">
            <h2>Listagem de despesas </h2>
        </div>
        <div class="col-md-12">

            <table class="table">
                <thead>

                    <tr>
                        <th>#</th>
                        <th>Descrição</th>
                        <th>Valor</th>
                        <th>Criado em</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>

                <?php foreach ($this->expenses as $e ): ?>
                    <tr>
                        <td> <?= $e['id']; ?>   </td>
                        <td> <?= $e['description']; ?>   </td>
                        <td> <?= "R$ ".number_format($e['value'], 2, ',', '.' ); ?>  </td>
                        <td> <?= date('d/m/Y H:i:s', strtotime($e['created_at'])); ?>   </td>
                        <td>
                            <a href="<?=HOME?>/myexpenses/edit/<?=$e['id']?> " class="btn btn-success">
                                EDITAR
                            </a>
                            <a href="<?=HOME?>/myexpenses/remove/<?=$e['id']?>" class="btn btn-danger">
                                REMOVER
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>

        </div>

    </div>




<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>